#!/bin/bash
UVER_VERSION=1.0
# Copyright(c) 2012 RubytotheRails.com
# This is free software distributed per the MIT License at www.r2dr.com/licenses/commands
# Copyright and License URL must be included for any distribution
function paint { echo $2; }
function colorOn { echo -n; }
function colorOff { echo -n; }
[[ -f "$(dirname $0)/colorize" ]] && source "$(dirname $0)/colorize"

if [[ $1 == "--version" ]]; then
	echo $UVER_VERSION
	exit
fi

colorOn yellow
lsb_release -a
echo ""
uname -a
echo ""
cat /proc/version
echo ""
colorOff
